add check mark icon with system vibrate when scan image
WeTransfer/WeScan pull request #331
Opened 2022-03-31 05:47 UTC by dipang90

2022-04-04 10:43 UTC, BasThomas commented
Hi @dipang90, thanks for your contribution!

Can you give some more information about this change? Perhaps post a video demonstrating the change?

2022-04-04 10:43 UTC, BasThomas commented
Hi @dipang90, thanks for your contribution!

Can you give some more information about this change? Perhaps post a video demonstrating the change?

2022-04-04 10:48 UTC, BasThomas commented on WeScan/Review/ReviewViewController.swift
> +        imageView.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 0.0)
To keep dark mode in mind, could we use a semantic color instead? Or if a specific color is required, use a named version?
```suggestion
        imageView.backgroundColor = .black
```

2022-04-04 10:48 UTC, BasThomas commented on WeScan/Review/ReviewViewController.swift
> +        AudioServicesPlaySystemSound(kSystemSoundID_Vibrate)
Why did you opt to use `AudioToolbox` over using haptics here? Could we instead consider using `UINotificationFeedbackGenerator`?

2022-04-04 10:48 UTC, BasThomas commented on WeScanSampleProject/Assets.xcassets/img_check.imageset/Contents.json
> +{
Does this look OK/as expected in both light and dark mode?

2022-05-02 09:39 UTC, kairadiagne requested changes
Awaiting feebdack on @BasThomas comments.

2022-06-13 00:10 UTC, closed without merging